function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "LabB_TuneTheGyro"};
	this.sidHashMap["LabB_TuneTheGyro"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "LabB_TuneTheGyro:579"};
	this.sidHashMap["LabB_TuneTheGyro:579"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "LabB_TuneTheGyro:314"};
	this.sidHashMap["LabB_TuneTheGyro:314"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "LabB_TuneTheGyro:556"};
	this.sidHashMap["LabB_TuneTheGyro:556"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/Clock"] = {sid: "LabB_TuneTheGyro:272"};
	this.sidHashMap["LabB_TuneTheGyro:272"] = {rtwname: "<Root>/Clock"};
	this.rtwnameHashMap["<Root>/Data Type  Conversion1"] = {sid: "LabB_TuneTheGyro:322"};
	this.sidHashMap["LabB_TuneTheGyro:322"] = {rtwname: "<Root>/Data Type  Conversion1"};
	this.rtwnameHashMap["<Root>/Gyro X Velocity"] = {sid: "LabB_TuneTheGyro:579"};
	this.sidHashMap["LabB_TuneTheGyro:579"] = {rtwname: "<Root>/Gyro X Velocity"};
	this.rtwnameHashMap["<Root>/calibrate the gyro before X seconds, start controlling after X seconds"] = {sid: "LabB_TuneTheGyro:314"};
	this.sidHashMap["LabB_TuneTheGyro:314"] = {rtwname: "<Root>/calibrate the gyro before X seconds, start controlling after X seconds"};
	this.rtwnameHashMap["<Root>/measurement filter"] = {sid: "LabB_TuneTheGyro:556"};
	this.sidHashMap["LabB_TuneTheGyro:556"] = {rtwname: "<Root>/measurement filter"};
	this.rtwnameHashMap["<S1>/Gyroscope1"] = {sid: "LabB_TuneTheGyro:577"};
	this.sidHashMap["LabB_TuneTheGyro:577"] = {rtwname: "<S1>/Gyroscope1"};
	this.rtwnameHashMap["<S1>/Mux"] = {sid: "LabB_TuneTheGyro:578"};
	this.sidHashMap["LabB_TuneTheGyro:578"] = {rtwname: "<S1>/Mux"};
	this.rtwnameHashMap["<S1>/Terminator"] = {sid: "LabB_TuneTheGyro:569"};
	this.sidHashMap["LabB_TuneTheGyro:569"] = {rtwname: "<S1>/Terminator"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "LabB_TuneTheGyro:580"};
	this.sidHashMap["LabB_TuneTheGyro:580"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/u"] = {sid: "LabB_TuneTheGyro:314:1"};
	this.sidHashMap["LabB_TuneTheGyro:314:1"] = {rtwname: "<S2>/u"};
	this.rtwnameHashMap["<S2>/Compare"] = {sid: "LabB_TuneTheGyro:314:2"};
	this.sidHashMap["LabB_TuneTheGyro:314:2"] = {rtwname: "<S2>/Compare"};
	this.rtwnameHashMap["<S2>/Constant"] = {sid: "LabB_TuneTheGyro:314:3"};
	this.sidHashMap["LabB_TuneTheGyro:314:3"] = {rtwname: "<S2>/Constant"};
	this.rtwnameHashMap["<S2>/y"] = {sid: "LabB_TuneTheGyro:314:4"};
	this.sidHashMap["LabB_TuneTheGyro:314:4"] = {rtwname: "<S2>/y"};
	this.rtwnameHashMap["<S3>/gyro bias"] = {sid: "LabB_TuneTheGyro:557"};
	this.sidHashMap["LabB_TuneTheGyro:557"] = {rtwname: "<S3>/gyro bias"};
	this.rtwnameHashMap["<S3>/enable the code below only when the external boolean input is true "] = {sid: "LabB_TuneTheGyro:277"};
	this.sidHashMap["LabB_TuneTheGyro:277"] = {rtwname: "<S3>/enable the code below only when the external boolean input is true "};
	this.rtwnameHashMap["<S3>/Scope"] = {sid: "LabB_TuneTheGyro:567"};
	this.sidHashMap["LabB_TuneTheGyro:567"] = {rtwname: "<S3>/Scope"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
